name        : xtrans
version     : 1.3.5
release     : 4
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/xtrans-1.3.5.tar.bz2 : adbd3b36932ce4c062cd10f57d78a156ba98d618bdb6f50664da327502bc8301
license     :
    - MIT
summary     : X Network Transport Base Code
component   : xorg.library
patterns    : /
description : |
    xtrans is a library of code that is shared among various X packages to handle network protocol transport in a modular fashion, allowing a single place to add new transport types.  It is used by the X server, libX11, libICE, the X font server, and related components.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
