name       : xtrans
version    : 1.4.0
release    : 8
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/xtrans-1.4.0.tar.gz : 48ed850ce772fef1b44ca23639b0a57e38884045ed2cbb18ab137ef33ec713f9
license    :
    - MIT
summary    : X Network Transport Base Code
component  : xorg.library
patterns   : /
description: |
    xtrans is a library of code that is shared among various X packages to handle network protocol transport in a modular fashion, allowing a single place to add new transport types.  It is used by the X server, libX11, libICE, the X font server, and related components.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
